// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8gd9r6Wf9y0nVwsyTO1_erCurJPAOB8s',
    appId: '1:564672519992:web:0f6e2c1d24c7ae48366bcd',
    messagingSenderId: '564672519992',
    projectId: 'habithero11',
    authDomain: 'habithero11.firebaseapp.com',
    storageBucket: 'habithero11.firebasestorage.app',
    measurementId: 'G-NF9DEWG5SK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1ydRo4VInukZqbDbtAE0GiHg0A6wVpYI',
    appId: '1:564672519992:android:2833cbaacd6f91fe366bcd',
    messagingSenderId: '564672519992',
    projectId: 'habithero11',
    storageBucket: 'habithero11.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPHLsFzowXImrntYwXwLjIxr0TEFtzOlk',
    appId: '1:564672519992:ios:f7171b22ce0c6576366bcd',
    messagingSenderId: '564672519992',
    projectId: 'habithero11',
    storageBucket: 'habithero11.firebasestorage.app',
    iosClientId: '564672519992-7idtrg6kcjb4ml8g3fu3qa6veuq0evs0.apps.googleusercontent.com',
    iosBundleId: 'com.example.habitHero',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPHLsFzowXImrntYwXwLjIxr0TEFtzOlk',
    appId: '1:564672519992:ios:f7171b22ce0c6576366bcd',
    messagingSenderId: '564672519992',
    projectId: 'habithero11',
    storageBucket: 'habithero11.firebasestorage.app',
    iosClientId: '564672519992-7idtrg6kcjb4ml8g3fu3qa6veuq0evs0.apps.googleusercontent.com',
    iosBundleId: 'com.example.habitHero',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8gd9r6Wf9y0nVwsyTO1_erCurJPAOB8s',
    appId: '1:564672519992:web:3f8654b387f3722a366bcd',
    messagingSenderId: '564672519992',
    projectId: 'habithero11',
    authDomain: 'habithero11.firebaseapp.com',
    storageBucket: 'habithero11.firebasestorage.app',
    measurementId: 'G-SPB9Z6ZRG0',
  );

}